### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by elevenpassin** [chingu-voyage4/Bears-Team-7#12]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
There is no set design for the project
**If you are reporting a bug, What is the expected behavior?**
N / A
**If the current behavior is a bug, please provide steps to reproduce**
N / A
**If you are requesting a feature, please explain the feature in detail**
We need to design the code editor first, a simple sketch in figma would suffice for now, so we know where to write code etc.

**Comment by Matthew-Burfield** [comment]
Based on discussions from tonights meeting, we are going to do a direct copy of the UX from vs code.
We want to be able to have a customizable and easily tweakable theming feature which we haven't fully scoped out yet.
We're just going to roll with a simple text box interface for the time being until we build up editing functionality were we can re-visit the design aspect then

**Comment by Matthew-Burfield** [comment]
Given that we've copied VS code's layout, I'm going to go and close this issue. We can open a new issue if we have a specific UI item we can work on
