### ISSUE TITLE
I can write code comfortably #1

### ISSUE THREAD

**Issue by elevenpassin** [chingu-voyage4/Bears-Team-7#13]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
The user can't do anything. :joy: 
**If you are reporting a bug, What is the expected behavior?**
N / A
**If the current behavior is a bug, please provide steps to reproduce**
N / A
**If you are requesting a feature, please explain the feature in detail**
A user should be able to type any letter or number in a div.

**Comment by Matthew-Burfield** [comment]
Just want to capture some stuff that we spoke about in our meeting in terms on implementation details.

We said that we'd go with our own custom div element as opposed to a textarea or other input component.
I think to sign off this issue, we just need a div that is listening for keyboard events, and if the event is a key press of a letter or number, that letter/number is outputted in the div.

**Comment by Matthew-Burfield** [comment]
Closed with PR #16
