### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by Matthew-Burfield** [chingu-voyage4/Bears-Team-7#31]
**If you are requesting a feature, please explain the feature in detail**

Add the ability to theme our code editor
We need a global styles variables file that can store all of our color variables etc.

I've also seen the syntax of <styles theme-name> inside Vue. Not sure how that works so we need to investigate that

**Comment by AlysCole** [comment]
May be able to use the [`stylus.import`](https://github.com/vuejs/vue-loader/issues/326#issuecomment-252505988) property to import a global variables stylus file without including an `@import` line in each and every `<style>` section.

**Comment by AlysCole** [comment]
For **SASS**, the [`data`](https://github.com/webpack-contrib/sass-loader#environment-variables) property of `sass-loader` can be used to prepend an `@import` at every styles file, as shown [here](https://github.com/webpack-contrib/sass-loader/issues/218#issuecomment-266669156).

**Comment by Matthew-Burfield** [comment]
Awesome @alyscole!! Did you get it working? I'll have a try this morning as well
