### ISSUE TITLE
Enter key pressed at the start of a line should insert a new line above the current line

### ISSUE THREAD

**Issue by AlysCole** [chingu-voyage4/Bears-Team-7#50]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
When the enter key is pressed with the caret at the beginning of an existing line, a new line is inserted below the current line.

**If you are reporting a bug, What is the expected behavior?**
The new line should be inserted _above_ the current line.

**Comment by Matthew-Burfield** [comment]
@AlysCole I think the latest commits fixed this bug, because I'm not seeing it anymore

**Comment by AlysCole** [comment]
Ah, right! You implemented `beforeBreak` and `afterBreak`.

#46 closed this issue.
