### ISSUE TITLE
Propose a suitable file structure

### ISSUE THREAD

**Issue by elevenpassin** [chingu-voyage4/Bears-Team-7#6]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behaviour?**
A decent file structure is absent.
**If you are reporting a bug, What is the expected behaviour?**
N / A
**If the current behaviour is a bug, please provide steps to reproduce**
N / A
**If you are requesting a feature, please explain the feature in detail**
Propose a good file structure to organise different components. Note that we have two root directories.
a `client` directory to store the client source code & a `server` directory for the server specifics.

**Comment by Matthew-Burfield** [comment]
I think the file structure we are using at the moment is pretty good. We don't have that many files anyway so this hasn't been a big issue.

I'm going to go and close this issue for now, and we can re-open a new issue if we need to re-address the file structure later, or if it becomes an issue
